[project]
name = "holoplus-mocked-api"
version = "0.0.1"
requires-python = ">=3.11,<4.0"
dependencies = [
    "litestar[standard]>=2.16.0,<3.0.0",
    "msgspec>=0.19.0,<1.0.0",
]

[tool.uv]
package = false
