[project]
name = "holoplus-tools"
version = "0.0.1"
requires-python = ">=3.11,<4.0"
dependencies = [
    "requests>=2.31.0,<3.0.0",
    "yt-dlp>=2025.9.5",
    "secretstorage>=3.4.0,<4.0.0",
]

[tool.uv]
package = false
